# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Use interactive function from Rcpp
#'
#' @export
interactive_rcpp <- function() {
    .Call(`_interactive_interactive_rcpp`)
}

